#!/usr/bin/python

'''
Created on Sep 1, 2011
@author: nicodejonghe

This is a quick script for setingup vhosts with a virtualbox vm
'''

import os
import sys
import shutil
import paramiko

drupalArg = raw_input('Create a drupal project, gitclone or new project [drupal/git/new]: ')

if str(drupalArg).lower() == 'drupal':
    FirstArg = 'drupal'
elif str(drupalArg).lower() == 'git':
    FirstArg = 'git'
else:
    FirstArg = 'new'

varProjectname = raw_input('Enter projectname please: ')
print 'A new project with the name', varProjectname, 'is build now'

def connectSsh ():
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect('192.168.56.101', username='nico', password='a')
    
    return ssh

def VMbashCommand (command):
    ssh = connectSsh()    

    stdin, stdout, stderr= ssh.exec_command(command)
    stdin.write('a\n')
    stdin.flush()
    
    stdout.readlines()
    stderr.readlines()

def localfileCommands ():
    if not os.path.exists('/home/nico/develop/php/' + varProjectname):
        os.mkdir('/home/nico/develop/php/'+ varProjectname)
        f = open('/home/nico/develop/php/' + varProjectname + '/index.php' ,'w')
        f.write( '<p>Remove me\n</p><p>' + varProjectname + '</p>' )
        f.close()

        if FirstArg == "drupal":
            #git://github.com/drupal/drupal.git
            os.remove('/home/nico/develop/php/' + varProjectname + '/index.php')
            print 'Downloading: Drupal lastest'
            os.system("cd /home/nico/develop/php/" + varProjectname + " && git clone git://github.com/drupal/drupal.git")
            print 'Downloaded: Drupal lastest only need to install the database '
            VMbashCommand("sudo -S sed -i 's/\/" + varProjectname + "/\/" + varProjectname + "\/drupal/g' /etc/apache2/sites-available/" + varProjectname)
            print 'Rewriting: Sites-available File', varProjectname

            print 'Starting: To set Drupal settings'
            print 'Creating : file directory'
            os.mkdir('/home/nico/develop/php/' + varProjectname + '/drupal/sites/default/files')
            print 'Copying : the default.settings.php file'
            shutil.copy2('/home/nico/develop/php/' + varProjectname + '/drupal/sites/default/default.settings.php', '/home/nico/develop/php/' + varProjectname + '/drupal/sites/default/settings.php')
            os.chmod('/home/nico/develop/php/' + varProjectname + '/drupal/sites/default/files', 0777)
            os.chmod('/home/nico/develop/php/' + varProjectname + '/drupal/sites/default/settings.php', 0777)
            #os.system("cd /home/nico/develop/php/" + varProjectname + " && git clone git://github.com/drupal/drupal.git");
            
            varVersionNumber = raw_input('Which version i need to checkout: ')
            
            if varVersionNumber == '6':
                os.system("cd /home/nico/develop/php/" + varProjectname + "/drupal/ && git checkout -b drupal6 origin/6.x")
            elif varVersionNumber == '7':
                print "Allready 7 default"
            elif varVersionNumber == '8':
                os.system("cd /home/nico/develop/php/" + varProjectname + "/drupal/ && git checkout -b drupal8 origin/8.x")
            else:
                print "Allready 7 default"

        elif FirstArg == "git":
            os.remove('/home/nico/develop/php/' + varProjectname + '/index.php')
            print 'Downloading: Drupal lastest'

            counter = 0
            varGitURL = str(raw_input('Enter GIT URL please: '))
            while True:
                counter = counter + 1

                if counter > 1:
                    varGitURL = str(raw_input('Do not enter empty a GIT URL please: '))

                if len(varGitURL) > 2:
                    os.system("cd /home/nico/develop/php/" + varProjectname + " && git clone " + varGitURL)
                    break;

    f = open('/etc/hosts', 'a')
    f.write( '192.168.56.101\t ' + varProjectname + ".dev\n" )
    f.close()

    varCreateAptanaProject = str(raw_input('Create a Aptana php project [y/n]'))

    if varCreateAptanaProject == 'y':
        f = open('/home/nico/develop/php/' + varProjectname + '/.buildpath','w')
        f.write('<?xml version="1.0" encoding="UTF-8"?>')
        f.write('<buildpath>')
        if FirstArg == "drupal":
            f.write('\t<buildpathentry kind="src" path="drupal"/>')
        else:
            f.write('\t<buildpathentry kind="src" path="./"/>')
        f.write('\t<buildpathentry kind="con" path="org.eclipse.php.core.LANGUAGE"/>')
        f.write('</buildpath>')
        f.close()
        
        f = open('/home/nico/develop/php/' + varProjectname + '/.project', 'w')
        f.write('<?xml version="1.0" encoding="UTF-8"?>')
        f.write('<projectDescription>')
        f.write('\t<name>' + varProjectname + '</name>')
        f.write('\t<comment></comment>')
        f.write('\t<projects>')
        f.write('\t</projects>')
        f.write('\t<buildSpec>')
        f.write('\t\t<buildCommand>')
        f.write('\t\t\t<name>org.eclipse.wst.validation.validationbuilder</name>')
        f.write('\t\t\t<arguments>')
        f.write('\t\t\t</arguments>')
        f.write('\t\t</buildCommand>')
        f.write('\t\t<buildCommand>')
        f.write('\t\t\t<name>org.eclipse.dltk.core.scriptbuilder</name>')
        f.write('\t\t\t<arguments>')
        f.write('\t\t\t</arguments>')
        f.write('\t\t</buildCommand>')
        f.write('\t</buildSpec>')
        f.write('\t<natures>')
        f.write('\t\t<nature>org.eclipse.php.core.PHPNature</nature>')
        f.write('\t</natures>')
        f.write('</projectDescription>')
        f.close()

        os.mkdir('/home/nico/develop/php/' + varProjectname + '/.settings')
        f = open('/home/nico/develop/php/' + varProjectname + '/.settings/org.eclipse.php.core.prefs', 'w')
        f.write('#Tue Sep 06 13:23:14 CEST 2011')
        f.write('eclipse.preferences.version=1')
        f.write('include_path=0;/' + varProjectname)
        f.close()

#		varDownloadjQueryProject = str(raw_input('Do we need to donwload jQuery [y/n]: '))
#		if varDownloadjQueryProject == 'y':
#			print 'not yet implemnted'



VMbashCommand("mysql -u root -proot -N -e 'CREATE DATABASE `" + varProjectname + "`;'")
print 'Created: database user: root - password: root - database name:', varProjectname
VMbashCommand("sudo -S echo '127.0.0.1 \t " + varProjectname + ".dev' >> /etc/hosts")
print 'Created: hosts rule on VM'
VMbashCommand("sudo -S cp /etc/apache2/sites-available/my-default /etc/apache2/sites-available/" + varProjectname)
print 'Created: File', varProjectname
VMbashCommand("sudo -S sed -i 's/my-default/" + varProjectname + "/g' /etc/apache2/sites-available/" + varProjectname)
print 'Writing: File', varProjectname
localfileCommands()
print 'Local Project: created'


VMbashCommand("sudo -S a2ensite " + varProjectname)
print 'Restarting server.....'
VMbashCommand("sudo -S service apache2 restart")

print "created new hosts rule on local and vm, also added new sites to apache2\n"
print "Structur" 
print 'end'    

exit()
